/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "https://esm.sh/ethers@6.7.0";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common.ts";

export interface KeysInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyKeys"
      | "changeKeyOwner"
      | "changeKeyType"
      | "claimHolderFee"
      | "claimableHolderFee"
      | "createKey"
      | "creatorFeePercent"
      | "deleteKey"
      | "exists"
      | "getBuyPrice"
      | "getBuyPriceAfterFee"
      | "getPrice"
      | "getSellPrice"
      | "getSellPriceAfterFee"
      | "groupHolderFeePercent"
      | "holders"
      | "hybridHolderFeePercent"
      | "hybridOwnerFeePercent"
      | "initialize"
      | "keys"
      | "nextKeyId"
      | "owner"
      | "protocolFeeDestination"
      | "protocolFeePercent"
      | "renounceOwnership"
      | "sellKeys"
      | "setCreatorFeePercent"
      | "setGroupHolderFeePercent"
      | "setHybridHolderFeePercent"
      | "setHybridOwnerFeePercent"
      | "setProtocolFeeDestination"
      | "setProtocolFeePercent"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChangeKeyOwner"
      | "ChangeKeyType"
      | "ClaimHolderFee"
      | "Initialized"
      | "KeyCreated"
      | "KeyDeleted"
      | "OwnershipTransferred"
      | "SetCreatorFeePercent"
      | "SetGroupHolderFeePercent"
      | "SetHybridHolderFeePercent"
      | "SetHybridOwnerFeePercent"
      | "SetProtocolFeeDestination"
      | "SetProtocolFeePercent"
      | "Trade"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyKeys",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeKeyOwner",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeKeyType",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimHolderFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableHolderFee",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createKey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deleteKey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPriceAfterFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPriceAfterFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "groupHolderFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "holders",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hybridHolderFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hybridOwnerFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "keys", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "nextKeyId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeDestination",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellKeys",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGroupHolderFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHybridHolderFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHybridOwnerFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeDestination",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "buyKeys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeKeyOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeKeyType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimHolderFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableHolderFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "groupHolderFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "holders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hybridHolderFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hybridOwnerFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keys", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextKeyId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeDestination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellKeys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGroupHolderFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHybridHolderFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHybridOwnerFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeDestination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ChangeKeyOwnerEvent {
  export type InputTuple = [
    keyId: BigNumberish,
    oldOwner: AddressLike,
    newOwner: AddressLike
  ];
  export type OutputTuple = [keyId: bigint, oldOwner: string, newOwner: string];
  export interface OutputObject {
    keyId: bigint;
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChangeKeyTypeEvent {
  export type InputTuple = [keyId: BigNumberish, keyType: BigNumberish];
  export type OutputTuple = [keyId: bigint, keyType: bigint];
  export interface OutputObject {
    keyId: bigint;
    keyType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimHolderFeeEvent {
  export type InputTuple = [
    holder: AddressLike,
    keyId: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [holder: string, keyId: bigint, fee: bigint];
  export interface OutputObject {
    holder: string;
    keyId: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyCreatedEvent {
  export type InputTuple = [
    keyId: BigNumberish,
    owner: AddressLike,
    keyType: BigNumberish
  ];
  export type OutputTuple = [keyId: bigint, owner: string, keyType: bigint];
  export interface OutputObject {
    keyId: bigint;
    owner: string;
    keyType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyDeletedEvent {
  export type InputTuple = [keyId: BigNumberish];
  export type OutputTuple = [keyId: bigint];
  export interface OutputObject {
    keyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetCreatorFeePercentEvent {
  export type InputTuple = [percent: BigNumberish];
  export type OutputTuple = [percent: bigint];
  export interface OutputObject {
    percent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetGroupHolderFeePercentEvent {
  export type InputTuple = [percent: BigNumberish];
  export type OutputTuple = [percent: bigint];
  export interface OutputObject {
    percent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetHybridHolderFeePercentEvent {
  export type InputTuple = [percent: BigNumberish];
  export type OutputTuple = [percent: bigint];
  export interface OutputObject {
    percent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetHybridOwnerFeePercentEvent {
  export type InputTuple = [percent: BigNumberish];
  export type OutputTuple = [percent: bigint];
  export interface OutputObject {
    percent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetProtocolFeeDestinationEvent {
  export type InputTuple = [destination: AddressLike];
  export type OutputTuple = [destination: string];
  export interface OutputObject {
    destination: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetProtocolFeePercentEvent {
  export type InputTuple = [percent: BigNumberish];
  export type OutputTuple = [percent: bigint];
  export interface OutputObject {
    percent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeEvent {
  export type InputTuple = [
    trader: AddressLike,
    keyId: BigNumberish,
    isBuy: boolean,
    amount: BigNumberish,
    price: BigNumberish,
    protocolFee: BigNumberish,
    ownerFee: BigNumberish,
    holderFee: BigNumberish,
    supply: BigNumberish
  ];
  export type OutputTuple = [
    trader: string,
    keyId: bigint,
    isBuy: boolean,
    amount: bigint,
    price: bigint,
    protocolFee: bigint,
    ownerFee: bigint,
    holderFee: bigint,
    supply: bigint
  ];
  export interface OutputObject {
    trader: string;
    keyId: bigint;
    isBuy: boolean;
    amount: bigint;
    price: bigint;
    protocolFee: bigint;
    ownerFee: bigint;
    holderFee: bigint;
    supply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Keys extends BaseContract {
  connect(runner?: ContractRunner | null): Keys;
  waitForDeployment(): Promise<this>;

  interface: KeysInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyKeys: TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;

  changeKeyOwner: TypedContractMethod<
    [keyId: BigNumberish, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  changeKeyType: TypedContractMethod<
    [keyId: BigNumberish, keyType: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimHolderFee: TypedContractMethod<
    [keyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimableHolderFee: TypedContractMethod<
    [keyId: BigNumberish, holder: AddressLike],
    [bigint],
    "view"
  >;

  createKey: TypedContractMethod<
    [keyType: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  creatorFeePercent: TypedContractMethod<[], [bigint], "view">;

  deleteKey: TypedContractMethod<[keyId: BigNumberish], [void], "nonpayable">;

  exists: TypedContractMethod<[keyId: BigNumberish], [boolean], "view">;

  getBuyPrice: TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getBuyPriceAfterFee: TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getPrice: TypedContractMethod<
    [supply: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getSellPrice: TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getSellPriceAfterFee: TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  groupHolderFeePercent: TypedContractMethod<[], [bigint], "view">;

  holders: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, bigint] & { balance: bigint; feeDebt: bigint }],
    "view"
  >;

  hybridHolderFeePercent: TypedContractMethod<[], [bigint], "view">;

  hybridOwnerFeePercent: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [
      _baseDivider: BigNumberish,
      _protocolFeeDestination: AddressLike,
      _protocolFeePercent: BigNumberish,
      _creatorFeePercent: BigNumberish,
      _groupHolderFeePercent: BigNumberish,
      _hybridOwnerFeePercent: BigNumberish,
      _hybridHolderFeePercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  keys: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        keyType: bigint;
        owner: string;
        supply: bigint;
        accFeePerUnit: bigint;
      }
    ],
    "view"
  >;

  nextKeyId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  protocolFeeDestination: TypedContractMethod<[], [string], "view">;

  protocolFeePercent: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sellKeys: TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCreatorFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGroupHolderFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHybridHolderFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHybridOwnerFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProtocolFeeDestination: TypedContractMethod<
    [_feeDestination: AddressLike],
    [void],
    "nonpayable"
  >;

  setProtocolFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyKeys"
  ): TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "changeKeyOwner"
  ): TypedContractMethod<
    [keyId: BigNumberish, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeKeyType"
  ): TypedContractMethod<
    [keyId: BigNumberish, keyType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimHolderFee"
  ): TypedContractMethod<[keyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableHolderFee"
  ): TypedContractMethod<
    [keyId: BigNumberish, holder: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createKey"
  ): TypedContractMethod<[keyType: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "creatorFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deleteKey"
  ): TypedContractMethod<[keyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "exists"
  ): TypedContractMethod<[keyId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBuyPrice"
  ): TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBuyPriceAfterFee"
  ): TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [supply: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellPrice"
  ): TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellPriceAfterFee"
  ): TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "groupHolderFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "holders"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, bigint] & { balance: bigint; feeDebt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hybridHolderFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hybridOwnerFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _baseDivider: BigNumberish,
      _protocolFeeDestination: AddressLike,
      _protocolFeePercent: BigNumberish,
      _creatorFeePercent: BigNumberish,
      _groupHolderFeePercent: BigNumberish,
      _hybridOwnerFeePercent: BigNumberish,
      _hybridHolderFeePercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "keys"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        keyType: bigint;
        owner: string;
        supply: bigint;
        accFeePerUnit: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextKeyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFeeDestination"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellKeys"
  ): TypedContractMethod<
    [keyId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCreatorFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGroupHolderFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHybridHolderFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHybridOwnerFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFeeDestination"
  ): TypedContractMethod<[_feeDestination: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ChangeKeyOwner"
  ): TypedContractEvent<
    ChangeKeyOwnerEvent.InputTuple,
    ChangeKeyOwnerEvent.OutputTuple,
    ChangeKeyOwnerEvent.OutputObject
  >;
  getEvent(
    key: "ChangeKeyType"
  ): TypedContractEvent<
    ChangeKeyTypeEvent.InputTuple,
    ChangeKeyTypeEvent.OutputTuple,
    ChangeKeyTypeEvent.OutputObject
  >;
  getEvent(
    key: "ClaimHolderFee"
  ): TypedContractEvent<
    ClaimHolderFeeEvent.InputTuple,
    ClaimHolderFeeEvent.OutputTuple,
    ClaimHolderFeeEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "KeyCreated"
  ): TypedContractEvent<
    KeyCreatedEvent.InputTuple,
    KeyCreatedEvent.OutputTuple,
    KeyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "KeyDeleted"
  ): TypedContractEvent<
    KeyDeletedEvent.InputTuple,
    KeyDeletedEvent.OutputTuple,
    KeyDeletedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SetCreatorFeePercent"
  ): TypedContractEvent<
    SetCreatorFeePercentEvent.InputTuple,
    SetCreatorFeePercentEvent.OutputTuple,
    SetCreatorFeePercentEvent.OutputObject
  >;
  getEvent(
    key: "SetGroupHolderFeePercent"
  ): TypedContractEvent<
    SetGroupHolderFeePercentEvent.InputTuple,
    SetGroupHolderFeePercentEvent.OutputTuple,
    SetGroupHolderFeePercentEvent.OutputObject
  >;
  getEvent(
    key: "SetHybridHolderFeePercent"
  ): TypedContractEvent<
    SetHybridHolderFeePercentEvent.InputTuple,
    SetHybridHolderFeePercentEvent.OutputTuple,
    SetHybridHolderFeePercentEvent.OutputObject
  >;
  getEvent(
    key: "SetHybridOwnerFeePercent"
  ): TypedContractEvent<
    SetHybridOwnerFeePercentEvent.InputTuple,
    SetHybridOwnerFeePercentEvent.OutputTuple,
    SetHybridOwnerFeePercentEvent.OutputObject
  >;
  getEvent(
    key: "SetProtocolFeeDestination"
  ): TypedContractEvent<
    SetProtocolFeeDestinationEvent.InputTuple,
    SetProtocolFeeDestinationEvent.OutputTuple,
    SetProtocolFeeDestinationEvent.OutputObject
  >;
  getEvent(
    key: "SetProtocolFeePercent"
  ): TypedContractEvent<
    SetProtocolFeePercentEvent.InputTuple,
    SetProtocolFeePercentEvent.OutputTuple,
    SetProtocolFeePercentEvent.OutputObject
  >;
  getEvent(
    key: "Trade"
  ): TypedContractEvent<
    TradeEvent.InputTuple,
    TradeEvent.OutputTuple,
    TradeEvent.OutputObject
  >;

  filters: {
    "ChangeKeyOwner(uint256,address,address)": TypedContractEvent<
      ChangeKeyOwnerEvent.InputTuple,
      ChangeKeyOwnerEvent.OutputTuple,
      ChangeKeyOwnerEvent.OutputObject
    >;
    ChangeKeyOwner: TypedContractEvent<
      ChangeKeyOwnerEvent.InputTuple,
      ChangeKeyOwnerEvent.OutputTuple,
      ChangeKeyOwnerEvent.OutputObject
    >;

    "ChangeKeyType(uint256,uint8)": TypedContractEvent<
      ChangeKeyTypeEvent.InputTuple,
      ChangeKeyTypeEvent.OutputTuple,
      ChangeKeyTypeEvent.OutputObject
    >;
    ChangeKeyType: TypedContractEvent<
      ChangeKeyTypeEvent.InputTuple,
      ChangeKeyTypeEvent.OutputTuple,
      ChangeKeyTypeEvent.OutputObject
    >;

    "ClaimHolderFee(address,uint256,uint256)": TypedContractEvent<
      ClaimHolderFeeEvent.InputTuple,
      ClaimHolderFeeEvent.OutputTuple,
      ClaimHolderFeeEvent.OutputObject
    >;
    ClaimHolderFee: TypedContractEvent<
      ClaimHolderFeeEvent.InputTuple,
      ClaimHolderFeeEvent.OutputTuple,
      ClaimHolderFeeEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "KeyCreated(uint256,address,uint8)": TypedContractEvent<
      KeyCreatedEvent.InputTuple,
      KeyCreatedEvent.OutputTuple,
      KeyCreatedEvent.OutputObject
    >;
    KeyCreated: TypedContractEvent<
      KeyCreatedEvent.InputTuple,
      KeyCreatedEvent.OutputTuple,
      KeyCreatedEvent.OutputObject
    >;

    "KeyDeleted(uint256)": TypedContractEvent<
      KeyDeletedEvent.InputTuple,
      KeyDeletedEvent.OutputTuple,
      KeyDeletedEvent.OutputObject
    >;
    KeyDeleted: TypedContractEvent<
      KeyDeletedEvent.InputTuple,
      KeyDeletedEvent.OutputTuple,
      KeyDeletedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SetCreatorFeePercent(uint256)": TypedContractEvent<
      SetCreatorFeePercentEvent.InputTuple,
      SetCreatorFeePercentEvent.OutputTuple,
      SetCreatorFeePercentEvent.OutputObject
    >;
    SetCreatorFeePercent: TypedContractEvent<
      SetCreatorFeePercentEvent.InputTuple,
      SetCreatorFeePercentEvent.OutputTuple,
      SetCreatorFeePercentEvent.OutputObject
    >;

    "SetGroupHolderFeePercent(uint256)": TypedContractEvent<
      SetGroupHolderFeePercentEvent.InputTuple,
      SetGroupHolderFeePercentEvent.OutputTuple,
      SetGroupHolderFeePercentEvent.OutputObject
    >;
    SetGroupHolderFeePercent: TypedContractEvent<
      SetGroupHolderFeePercentEvent.InputTuple,
      SetGroupHolderFeePercentEvent.OutputTuple,
      SetGroupHolderFeePercentEvent.OutputObject
    >;

    "SetHybridHolderFeePercent(uint256)": TypedContractEvent<
      SetHybridHolderFeePercentEvent.InputTuple,
      SetHybridHolderFeePercentEvent.OutputTuple,
      SetHybridHolderFeePercentEvent.OutputObject
    >;
    SetHybridHolderFeePercent: TypedContractEvent<
      SetHybridHolderFeePercentEvent.InputTuple,
      SetHybridHolderFeePercentEvent.OutputTuple,
      SetHybridHolderFeePercentEvent.OutputObject
    >;

    "SetHybridOwnerFeePercent(uint256)": TypedContractEvent<
      SetHybridOwnerFeePercentEvent.InputTuple,
      SetHybridOwnerFeePercentEvent.OutputTuple,
      SetHybridOwnerFeePercentEvent.OutputObject
    >;
    SetHybridOwnerFeePercent: TypedContractEvent<
      SetHybridOwnerFeePercentEvent.InputTuple,
      SetHybridOwnerFeePercentEvent.OutputTuple,
      SetHybridOwnerFeePercentEvent.OutputObject
    >;

    "SetProtocolFeeDestination(address)": TypedContractEvent<
      SetProtocolFeeDestinationEvent.InputTuple,
      SetProtocolFeeDestinationEvent.OutputTuple,
      SetProtocolFeeDestinationEvent.OutputObject
    >;
    SetProtocolFeeDestination: TypedContractEvent<
      SetProtocolFeeDestinationEvent.InputTuple,
      SetProtocolFeeDestinationEvent.OutputTuple,
      SetProtocolFeeDestinationEvent.OutputObject
    >;

    "SetProtocolFeePercent(uint256)": TypedContractEvent<
      SetProtocolFeePercentEvent.InputTuple,
      SetProtocolFeePercentEvent.OutputTuple,
      SetProtocolFeePercentEvent.OutputObject
    >;
    SetProtocolFeePercent: TypedContractEvent<
      SetProtocolFeePercentEvent.InputTuple,
      SetProtocolFeePercentEvent.OutputTuple,
      SetProtocolFeePercentEvent.OutputObject
    >;

    "Trade(address,uint256,bool,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
    Trade: TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
  };
}
